export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const SENDMSG_SUCCESSFUL ="SENDMSG_SUCCESSFUL";
export const SENDMSG_FAIL = 'SENDMSG_FAIL';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const ADD_CHANNEL = 'ADD_CHANNEL';


